version: '3.8'

services:
  app:
    build:
      context: .
    container_name: tratofeito-app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8080"
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tratofeito
      DB_USERNAME: postgres
      DB_PASSWORD: secret
      REDIS_HOST: redis
    command: php artisan serve --host=0.0.0.0 --port=8080

  db:
    image: postgres:15
    container_name: tratofeito-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: tratofeito
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: tratofeito-redis
    ports:
      - "6379:6379"
